version: '3'
services:
  todo-node:
    build:
      context: ./
      dockerfile: Dockerfile
    image: todo-node
    container_name: todo-node
    volumes:
      - ./:/home/
    env_file:
      - ./.env.local
    ports:
      - 8400:8400
    depends_on:
      - mongo-todo-node
  mongo-todo-node:
    image: mongo:8.0
    container_name: mongo-todo-node
    volumes:
      - mongo-volume-todo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 42080:27017
volumes:
  mongo-volume-todo: